import Head from 'next/head';
import Button from '@src/components/Button';
import Form from '@src/components/Form';
import InputField from '@src/components/InputField';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Form>
          <InputField label={'Username'} />
          <InputField label={'Password'} type={'password'} />
          <Button title="Login" />
        </Form>
      </main>
    </>
  );
}
