import Head from 'next/head';
import GitHub_Icon from '@src/components/Icons/GitHub/gitHub_Icon';
import Icon from '@src/components/Icons/icon';
import Text from '@src/components/Text/text';
import theme from '@src/styles/themes';
import MediaImage from '@src/components/Image/image';
import imgAndersonMiranda from '@src/assets/images/MirandinhaDev.jpg';
import NavLink from '@src/components/Link/navLink';
import React_Icon from '@src/components/Icons/React/react_icon';

export default function HomeScreen() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ display: 'flex', flexDirection: 'column' }}>
        <Text styleSheet={{ fontFamily: theme.tipography.font1.fontFamily }}>
          Setup Next JS with TypesScript, Eslint, Prettier, Styled-Componentes, Jest/React testing library
        </Text>
        <ul>
          <Icon href={'https://google.com'} size="50px">
            <GitHub_Icon fill="orange" />
          </Icon>
          <Icon href="https://youtube.com" size="50px">
            <React_Icon />
          </Icon>
          <NavLink
            href={'./screen_2'}
            styleSheet={{ color: 'purple', fontSize: '3rem', fontFamily: theme.tipography.font1.fontFamily }}
          >
            Screen_2
          </NavLink>
        </ul>
        <MediaImage src={imgAndersonMiranda} alt="Image name" styleSheet={{ width: '350px', borderRadius: '20px' }} />
      </main>
    </>
  );
}
